"""Render the final context document."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from .git_analyzer import GitSummary
from .token_budget import BudgetAllocation


_LANGUAGE_MAP = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".java": "java",
    ".kt": "kotlin",
    ".swift": "swift",
    ".c": "c",
    ".cpp": "cpp",
    ".h": "c",
    ".hpp": "cpp",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".toml": "toml",
    ".md": "markdown",
    ".html": "html",
    ".css": "css",
    ".sql": "sql",
    ".dockerfile": "dockerfile",
}


def _lang(path: Path) -> str:
    name = path.name.lower()
    if name == "dockerfile":
        return "dockerfile"
    return _LANGUAGE_MAP.get(path.suffix.lower(), "")


def render_context(
    repo_root: Path,
    selected_files: list,   # list of (RankedFile, content, token_count)
    git_summary: GitSummary,
    allocation: BudgetAllocation,
    repo_name: Optional[str] = None,
) -> str:
    """Render the full context document as a markdown string."""
    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    name = repo_name or repo_root.name
    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        f"# Codebase Context: {name}",
        f"> Generated by codebrief · {now}",
        f"> Token budget: {allocation.total_budget:,} · Used: {allocation.budget_used:,} ({allocation.utilization_pct:.0f}%)",
        f"> Files included: {allocation.files_included} · Skipped (budget): {allocation.files_skipped}",
        "",
    ]

    # ── Git Summary ────────────────────────────────────────────────────────────
    if git_summary.total_commits_analyzed > 0:
        lines += [
            "## Repository Activity",
            f"- **Branch:** `{git_summary.branch}`",
            f"- **Commits analyzed:** {git_summary.total_commits_analyzed}",
        ]
        if git_summary.active_authors:
            lines.append(f"- **Active contributors:** {', '.join(git_summary.active_authors)}")
        if git_summary.most_changed_files:
            hotspots = ", ".join(f"`{f}`" for f in git_summary.most_changed_files[:5])
            lines.append(f"- **Hotspot files:** {hotspots}")
        lines.append("")

        if git_summary.recent_commits:
            lines.append("### Recent Commits")
            for c in git_summary.recent_commits[:10]:
                lines.append(f"- `{c['sha']}` {c['message']} _{c['author']}_")
            lines.append("")

    # ── File Tree ──────────────────────────────────────────────────────────────
    lines += ["## Included Files", ""]
    for rf, _content, tokens in selected_files:
        flag = " 🔥" if rf.is_recently_changed else ""
        lines.append(f"- `{rf.relative_path}` ({tokens:,} tokens){flag}")
    lines.append("")

    # ── File Contents ─────────────────────────────────────────────────────────
    lines.append("## File Contents")
    lines.append("")

    for rf, content, tokens in selected_files:
        lang = _lang(rf.path)
        flag = " _(recently changed)_" if rf.is_recently_changed else ""
        lines += [
            f"### `{rf.relative_path}`{flag}",
            "",
            f"```{lang}",
            content.rstrip(),
            "```",
            "",
        ]

    return "\n".join(lines)
